package com.ampere.batterylab;

import android.content.Context;
import android.content.res.Configuration;
import android.os.Build;
import java.util.Locale;

/** Small, dependency-free UI language layer used by the custom canvas and services. */
final class AppText {
    private AppText() {}

    static boolean isEnglish(Context context) {
        if (context == null) return "en".equalsIgnoreCase(Locale.getDefault().getLanguage());
        Configuration configuration = context.getResources().getConfiguration();
        Locale locale;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            locale = configuration.getLocales().isEmpty()
                    ? Locale.getDefault() : configuration.getLocales().get(0);
        } else {
            //noinspection deprecation
            locale = configuration.locale == null ? Locale.getDefault() : configuration.locale;
        }
        return "en".equalsIgnoreCase(locale.getLanguage());
    }

    /** Locale used by every user-visible numeric value, including widgets and services. */
    static Locale uiLocale(Context context) {
        return isEnglish(context) ? Locale.US : Locale.GERMANY;
    }

    static String t(Context context, String value) {
        // Use the context locale here instead of Locale.getDefault(). Android
        // supports an app-specific language, so the app can be English while
        // the rest of the device remains in another language.
        return isEnglish(context) ? translate(value) : value;
    }

    /**
     * Translates the UI vocabulary while preserving numbers, units, app names
     * and server-provided values. The method intentionally leaves unknown
     * strings untouched so diagnostics and user data are never corrupted.
     */
    static String t(String value) {
        if (value == null || value.isEmpty()
                || !"en".equalsIgnoreCase(Locale.getDefault().getLanguage())) return value;
        return translate(value);
    }

    private static String translate(String value) {
        if (value == null || value.isEmpty()) return value;
        String result = value;
        String[][] phrases = {
                {"Beobachte deinen Akku", "Monitor your battery"},
                {"Akkuverbrauch deiner Apps", "Battery usage by app"},
                {"Dein Akku im Zeitverlauf", "Your battery over time"},
                {"Dein Tagesrhythmus", "Your daily pattern"},
                {"Akkugesundheit", "Battery health"},
                {"Akkukapazität", "Battery capacity"},
                {"Akkuzustand", "Battery status"},
                {"Akkuinformationen werden geladen.", "Loading battery information."},
                {"Alles läuft", "Everything is running"},
                {"ganz entspannt.", "smoothly."},
                {"Noch nicht gemessen", "Not measured yet"},
                {"Finde Kapazität und Verschleiß heraus.", "Measure capacity and battery wear."},
                {"Messung aktualisieren", "Refresh measurement"},
                {"Messung starten", "Start measurement"},
                {"Designkapazität", "Design capacity"},
                {"Gemessene Kapazität", "Measured capacity"},
                {"AKKUSTAND · AUTOMATISCH", "BATTERY LEVEL · AUTOMATIC"},
                {"AKKUSTAND · AUTOMATIK", "BATTERY LEVEL · AUTOMATIC"},
                {"AKKUGESUNDHEIT", "BATTERY HEALTH"},
                {"AKKUSTAND", "BATTERY LEVEL"},
                {"LÄDT JETZT", "CHARGING NOW"},
                {"AKKUBETRIEB", "ON BATTERY"},
                {"UNTERWEGS MIT AKKU", "ON THE GO"},
                {"DEIN AKKU-MUSTER", "YOUR BATTERY PATTERN"},
                {"DEIN AKKU-TAGEBUCH", "YOUR BATTERY JOURNAL"},
                {"LIVE & SITZUNG", "LIVE & SESSION"},
                {"APP-VERBRAUCH · GESCHÄTZT", "APP USAGE · ESTIMATED"},
                {"ALLE APP-DETAILS ANSEHEN  →", "VIEW ALL APP DETAILS  →"},
                {"Ø VERBRAUCH", "AVERAGE USAGE"},
                {"am Ende der Entladung", "at the end of discharge"},
                {"aktueller Akkustand", "current battery level"},
                {"Gerät wird geladen", "Device is charging"},
                {"Sitzung startet beim Abstecken", "Session starts when unplugged"},
                {"Bildschirm an", "Screen on"}, {"Bildschirm aus", "Screen off"},
                {"Bildschirm an / aus", "Screen on / off"},
                {"Nach dem Abstecken", "After unplugging"},
                {"Entladung starten", "Start a discharge session"},
                {"Ladeziel erreicht", "Charge target reached"},
                {"Hohe Akkutemperatur", "High battery temperature"},
                {"Akku fast leer", "Battery nearly empty"},
                {"eingestelltes Ziel", "set target"}, {"Grenzwert", "threshold"},
                {"CPU gesamt", "Total CPU"}, {"Vordergrund-App", "Foreground app"},
                {"Prozesslast", "Process load"},
                {"Normale Nutzung", "Normal use"}, {"Mehr Daten", "More data"},
                {"seit dem Abstecken", "since unplugging"},
                {"Seit dem Abstecken", "Since unplugging"},
                {"Seit dem Abstecken · geschätzte Werte", "Since unplugging · estimated values"},
                {"Ø Entladerate", "Average discharge rate"}, {"Entladerate", "Discharge rate"},
                {"Tiefschlaf", "Deep sleep"},
                {"Verbrauch seit dem Abstecken", "Usage since unplugging"},
                {"LIVE · GERÄT", "LIVE · DEVICE"},
                {"LADEBEGLEITUNG", "CHARGE COMPANION"},
                {"AKTUELL", "CURRENT"},
                {"RATE JETZT", "CURRENT RATE"},
                {"TEMPERATUR · SPANNUNG", "TEMPERATURE · VOLTAGE"},
                {"SENSOREN", "SENSORS"},
                {"Volle Kapazität", "Full capacity"},
                {"Nennkapazität", "Design capacity"},
                {"Nennwert", "Design value"},
                {"Alarm bei", "Alert at"},
                {"kein Ladestopp", "no charge stop"},
                {"Laden im Blick.", "Charging at a glance."},
                {"Bereit zum Laden.", "Ready to charge."},
                {"Fortschritt zum Ladeziel", "Progress toward charge target"},
                {"Benachrichtigt dich bei", "Notifies you at"},
                {"Zurzeit ausgeschaltet", "Currently disabled"},
                {"Live-Anzeige", "Live overlay"},
                {"Schwebt über anderen Apps", "Floats over other apps"},
                {"Über anderen Apps ausgeblendet", "Hidden over other apps"},
                {"Quelle: ", "Source: "},
                {"Status · Quelle", "Status · source"},
                {"Zeit bis Ladeziel", "Time to charge target"},
                {"Länger laden für eine Schätzung", "Charge longer for an estimate"},
                {"AKKUVERBRAUCH", "BATTERY USAGE"},
                {"ÄNDERUNG", "CHANGE"}, {"DAUER", "DURATION"}, {"GESTARTET", "STARTED"},
                {"GESCHÄTZTE RESTLAUFZEIT BIS 0 %", "ESTIMATED TIME REMAINING TO 0%"},
                {"Noch keine Messung", "No measurement yet"},
                {"Eine volle Ladung", "A full charge"},
                {"SYSTEMDATEN AKTIV", "SYSTEM DATA ACTIVE"},
                {"SO ENTSTEHT DIE SCHÄTZUNG", "HOW THE ESTIMATE IS CALCULATED"},
                {"NENNKAPAZITÄT", "DESIGN CAPACITY"},
                {"ANTIPPEN ZUM ÄNDERN", "TAP TO EDIT"},
                {"Nur lokal gespeichert.", "Stored locally only."},
                {"PRIVAT VON ANFANG AN", "PRIVATE BY DESIGN"},
                {"ANALYSEZENTRALE", "ANALYSIS CENTER"},
                {"LADEVORGANG", "CHARGING SESSION"},
                {"LADEMENGE", "CHARGE AMOUNT"},
                {"VERBLEIBENDE NUTZUNGSZEIT", "REMAINING RUNTIME"},
                {"KAPAZITÄTSSCHÄTZUNG", "CAPACITY ESTIMATE"},
                {"LADEGESCHWINDIGKEIT", "CHARGING SPEED"},
                {"ENTLADEVORGANG", "DISCHARGE SESSION"},
                {"An ", "On "}, {" · aus ", " · off "},
                {"Bildschirm-Aufweckungen", "screen wake-ups"},
                {"TÄGLICHE VOLLZYKLEN", "DAILY FULL CYCLES"},
                {"LADEVERSCHLEISS", "CHARGING WEAR"},
                {"AUSWERTUNG", "ANALYSIS"}, {"LETZTE SITZUNGEN", "RECENT SESSIONS"},
                {"VERLAUF", "HISTORY"}, {"DIAGNOSE", "DIAGNOSTICS"},
                {"Sitzungen:", "Sessions:"}, {"Ladungsmenge:", "Charge amount:"},
                {"VERLAUF & STATISTIK", "HISTORY & STATISTICS"},
                {"Lokal aus Messpunkten berechnet · keine Cloud", "Calculated locally from measurements · no cloud"},
                {"DIESER MONAT · MONATSANFANG BIS HEUTE", "THIS MONTH · START OF MONTH TO TODAY"},
                {"Aufgeladen", "Charged"}, {"Batterieverbrauch", "Battery usage"},
                {"Geladen", "Charged"}, {"Ladequote", "Charge ratio"},
                {"Mär", "Mar"}, {"Mai", "May"}, {"Juni", "June"},
                {"Juli", "July"}, {"Okt", "Oct"}, {"Dez", "Dec"},
                {"Sept", "Sep"}, {"Mo.", "Mon"}, {"Di.", "Tue"},
                {"Mi.", "Wed"}, {"Do.", "Thu"}, {"Fr.", "Fri"},
                {"Sa.", "Sat"}, {"So.", "Sun"},
                {"Geladen/Usage", "Charged/usage"},
                {"Woche", "Week"}, {"Monat", "Month"}, {"day", "Day"},
                {"Werte des aktiven Bereichs", "Values for the active section"},
                {"Gut lesbare Akkuwerte · live aktualisiert", "Readable battery values · updated live"},
                {"Berechtigungen & Zugriffe", "Permissions & access"},
                {"App-Akkuverbrauch", "App battery usage"},
                {"Akku-Bilanz", "Battery balance"},
                {"Sitzungsdetails", "Session details"},
                {"Letzte 24 Stunden", "Last 24 hours"},
                {"Letzte 7 Tage", "Last 7 days"},
                {"Letzte 30 Tage", "Last 30 days"},
                {"Täglich", "Daily"}, {"Wöchentlich", "Weekly"}, {"Monatlich", "Monthly"},
                {"Übersicht", "Overview"}, {"Start", "Home"}, {"Laden", "Charging"},
                {"Entladen", "Discharging"}, {"Akku", "Battery"}, {"Verlauf", "History"},
                {"Gesundheit", "Health"}, {"Einstellungen", "Settings"},
                {"Aktionen", "Actions"}, {"Ladeziel", "Charge target"},
                {"Akkustand", "Battery level"}, {"Akkustrom", "Battery current"},
                {"Startbildschirm", "Home screen"}, {"Unbekannte App", "Unknown app"},
                {"Akkuspannung", "Battery voltage"}, {"Akkuleistung", "Battery power"},
                {"Akkutemperatur", "Battery temperature"}, {"Temperatur", "Temperature"},
                {"Spannung", "Voltage"}, {"Verbrauch", "Usage"}, {"Akkuverbrauch", "Battery usage"},
                {"Bildschirmzeit", "Screen time"}, {"Ladezyklen", "Charge cycles"},
                {"Lernen braucht", "Learning takes"}, {"ein wenig Zeit.", "a little time."},
                {"Eine volle Ladung", "One full charge"}, {"schafft die Messbasis", "provides the baseline"},
                {"geeignete Sitzungen", "valid sessions"},
                {"Kapazitätsmessung weiter unten starten", "Start capacity measurement below"},
                {"Systemzyklen", "System cycles"}, {"von Android gemeldet", "reported by Android"},
                {"Android-Testwert", "Android test value"}, {"Android-Akkusensor", "Android battery sensor"},
                {"Ampere-Vollzyklen", "Ampere full cycles"}, {"MESSBASIS", "MEASUREMENT BASELINE"},
                {"VOLLE KAPAZITÄT", "FULL CAPACITY"}, {"AKKUSPANNUNG", "BATTERY VOLTAGE"},
                {"SYSTEMZYKLEN", "SYSTEM CYCLES"},
                {"BILDSCHIRM", "SCREEN"}, {"VERBRAUCH", "USAGE"},
                {"aktive Nutzung", "active use"}, {"geschätzte Werte", "estimated values"},
                {"Verbrauchte Ladung", "Charge used"}, {"Verbrauchte Energie", "Energy used"},
                {"Geladen/Verbrauch", "Charged/used"}, {"Akkuverschleiß", "Battery wear"},
                {"Verschleiß", "Wear"}, {"Effizienz", "Efficiency"}, {"Sitzungen", "Sessions"},
                {"Ladeeingang", "Charging input"}, {"Akkuseite", "Battery side"},
                {"Aktueller Akkustand", "Current battery level"}, {"aktueller Akkustand", "current battery level"},
                {"Aktualisiert live", "Updated live"}, {"Warte auf Strommessung", "Waiting for current measurement"},
                {"Warte auf Android-Akkuwert", "Waiting for Android battery value"},
                {"Nicht verfügbar", "Not available"}, {"nicht verfügbar", "not available"},
                {"Keine Daten", "No data"}, {"Noch keine Daten", "No data yet"},
                {"Noch keine Verbrauchsdaten für die Quote", "No usage data for the ratio yet"},
                {"Wird gemessen", "Measuring"}, {"Noch offen", "Pending"}, {"gerade eben", "just now"},
                {"BERECHNET", "CALCULATED"}, {"GESCHÄTZT", "ESTIMATED"}, {"SYSTEM", "SYSTEM"},
                {"LIVE", "LIVE"}, {"AKKUVERBRAUCH", "BATTERY USAGE"}, {"Lade-/Verbrauchsquote", "charge/usage ratio"},
                {"lokale Verlaufseinträge zu erstellen.", "to create local history entries."},
                {"Akkumesswerte bleiben auf diesem Gerät.", "Battery measurements stay on this device."},
                {"Weitere Sitzungen im Verlauf", "More sessions in history"},
                {"Verbrauch den verwendeten Apps zu.", "Usage attributed to the apps used."},
                {"Wärme prüfen", "Check temperature"}, {"Unbekannt", "Unknown"},
                {"Temperaturwarnung", "Temperature alert"}, {"Tiefstandwarnung", "Low battery alert"},
                {"Datenerfassung", "Data collection"}, {"Hintergrundüberwachung", "Background monitoring"},
                {"Daten & Datenschutz", "Data & privacy"}, {"Nutzungsanalyse", "Usage analytics"},
                {"Sicherung & Wiederherstellung", "Backup & restore"},
                {"Benachrichtigungen", "Notifications"}, {"Berechtigungen prüfen", "Check permissions"},
                {"Ladeziel & Ladealarm", "Charge target & alert"}, {"Overlay-Berechtigung", "Overlay permission"},
                {"Nach Updates suchen", "Check for updates"}, {"Kurzanleitung", "Quick guide"},
                {"Aktuellen Status kopieren", "Copy current status"}, {"Aktuellen Status teilen", "Share current status"},
                {"Gesundheitsbasis zurücksetzen", "Reset health baseline"},
                {"Temperaturwarnung · ab ", "Temperature alert · at "}, {"Temperaturwarnung · aus", "Temperature alert · off"},
                {"Tiefstandwarnung · bei ", "Low battery alert · at "}, {"Tiefstandwarnung · aus", "Low battery alert · off"},
                {"Datenerfassung · alle ", "Data collection · every "}, {"Minuten", "minutes"},
                {"Temperaturwarnung · Rücksetzung 3 °C darunter", "Temperature alert · resets 3 °C below"},
                {"Tiefstandwarnung · Rücksetzung mit 3 % Abstand", "Low battery alert · resets with a 3% margin"},
                {"Datenerfassung · nur lokal", "Data collection · local only"},
                {"Aus", "Off"}, {"Ab ", "At "}, {"Bei ", "At "}, {"oder weniger", "or less"},
                {"(empfohlen)", "(recommended)"}, {"Alle ", "Every "},
                {"Abbrechen", "Cancel"}, {"Speichern", "Save"}, {"Schließen", "Close"},
                {"Einstellungen schließen", "Close settings"}, {"Akku-Einstellungen", "Battery settings"},
                {"Berechtigungen & Zugriffe", "Permissions & access"}, {"Fertig", "Done"},
                {"Aktiv", "Active"}, {"Nicht erteilt", "Not granted"}, {"optional", "optional"},
                {"Optional · nicht aktiviert", "Optional · not enabled"},
                {"Live-Status und Alarme", "Live status and alerts"},
                {"App-Nutzungszugriff", "App usage access"}, {"Verbrauch je App", "Usage by app"},
                {"Nicht erteilt · optional", "Not granted · optional"},
                {"Overlay", "Overlay"}, {"Live-Anzeige", "Live overlay"},
                {"Einige Zugriffe fehlen oder wurden von Android zurückgesetzt.", "Some accesses are missing or were reset by Android."},
                {"Ampere prüft sie beim Öffnen erneut", "Ampere checks them again when opened"},
                {"abgelehnte optionale Zugriffe melden wir höchstens monatlich.", "we remind you about declined optional accesses at most once a month."},
                {"Widerrufe erkennen wir beim nächsten Öffnen.", "We detect revoked access the next time you open the app."},
                {"Benachrichtigungen ermöglichen Live-Status und Ladealarme.", "Notifications enable live status and charge alerts."},
                {"App-Nutzungszugriff zeigt den Verbrauch je App", "App usage access shows usage by app"},
                {"Overlay zeigt die Live-Anzeige über anderen Apps.", "Overlay shows the live display over other apps."},
                {"Diese beiden Zugriffe sind optional.", "These two accesses are optional."},
                {"Ampere prüft den Status beim Öffnen erneut.", "Ampere checks their status again when opened."},
                {"Tippe auf einen Eintrag, um ihn zu ändern.", "Tap an entry to change it."},
                {"Temperaturwarnung ausgeschaltet", "Temperature alert turned off"},
                {"Tiefstandwarnung ausgeschaltet", "Low battery alert turned off"},
                {"Hintergrundüberwachung ist ab Android 6 verfügbar.", "Background monitoring is available from Android 6."},
                {"Einstellungen", "Settings"},
                {"Lokale Daten löschen?", "Delete local data?"},
                {"Gesundheitsbasis zurücksetzen?", "Reset health baseline?"},
                {"Backup gespeichert.", "Backup saved."}, {"Backup wiederhergestellt.", "Backup restored."},
                {"Backup konnte nicht gespeichert werden.", "Backup could not be saved."},
                {"Backup ist ungültig oder konnte nicht gelesen werden.", "Backup is invalid or could not be read."},
                {"CSV-Export gespeichert.", "CSV export saved."}, {"Diagnosebericht gespeichert.", "Diagnostic report saved."},
                {"CSV-Export konnte nicht gespeichert werden.", "CSV export could not be saved."},
                {"Diagnosebericht konnte nicht gespeichert werden.", "Diagnostic report could not be saved."},
                {"Forschungs-Export gespeichert.", "Research export saved."},
                {"Forschungs-Export konnte nicht gespeichert werden.", "Research export could not be saved."},
                {"Live-Daten aktualisiert.", "Live data updated."},
                {"Akkuüberwachung", "Battery monitoring"}, {"Ladealarm", "Charge alert"},
                {"Warte auf Akkudaten", "Waiting for battery data"},
                {"Letzter Entladevorgang", "Last discharge"},
                {"Zusammenfassung.", "summary."},
                {"Bereit für Entladung.", "Ready for discharge."},
                {"Startet beim Abstecken.", "Starts when unplugged."},
                {"Telemetrie-Schätzung", "Telemetry estimate"},
                {"Vordergrundzeit-Schätzung", "Foreground-time estimate"},
                {"Akkuverbrauch nicht verfügbar", "Battery usage unavailable"},
                {"Zurück", "Back"}, {"SCHLIESSEN", "CLOSE"},
                {"ausgewählt", "selected"},
                {"Verlauf täglich", "Daily history"}, {"Verlauf wöchentlich", "Weekly history"},
                {"Verlauf monatlich", "Monthly history"},
                {"CSV exportieren", "Export CSV"},
                {"Exakte Werte im Bilanzdiagramm anzeigen", "Show exact values in the balance chart"},
                {"Kapazitätsmessung stoppen", "Stop capacity measurement"},
                {"Kapazität messen", "Measure capacity"},
                {"Nennkapazität bearbeiten", "Edit design capacity"},
                {"Restlaufzeit bei dauerhaft eingeschaltetem Bildschirm", "Runtime with screen always on"},
                {"Restlaufzeit bei ausgeschaltetem Bildschirm", "Runtime with screen off"},
                {"Restlaufzeit bei normaler Nutzung", "Runtime with normal use"},
                {"Bildschirm dauerhaft an", "Screen always on"},
                {"Ladealarm: ", "Charge alert: "}, {"Live-Anzeige: ", "Live overlay: "},
                {"Ladeziel: ", "Charge target: "},
                {"Akku ist voll", "Battery is full"},
                {"Akku wird geladen", "Charging now"},
                {"Akku entlädt sich", "Battery is discharging"},
                {"Akkubetrieb aktiv", "On battery"},
                {"Keine Daten verfügbar.", "No data available."},
                {"Bereit für die Nutzung.", "Ready to use."},
                {"Laden wird überwacht.", "Charging is monitored."},
                {"Verbrauch wird live erfasst.", "Usage is tracked live."},
                {"Überwachung läuft weiter.", "Monitoring continues."},
                {"Live-Akkuanzeige", "Live battery overlay"},
                {"App-Aktualisierungen", "App updates"},
                {"Update verfügbar · ", "Update available · "},
                {"Ampere-Update verfügbar · ", "Ampere update available · "},
                {"Die kostenlose APK wird vor der Installation auf Hash, Paketname, Version und Release-Signatur geprüft. Android fragt anschließend noch einmal nach deiner Bestätigung.", "Before installation, the free APK is checked for its hash, package name, version and release signature. Android will ask for your confirmation once more."},
                {"Später", "Later"}, {"Herunterladen", "Download"},
                {"Tippen, um die kostenlose Aktualisierung zu prüfen", "Tap to verify the free update"},
                {"Download ist auf diesem Gerät nicht verfügbar.", "Downloads are not available on this device."},
                {"Update konnte nicht sicher vorbereitet werden.", "The update could not be prepared safely."},
                {"Update wird heruntergeladen …", "Downloading update …"},
                {"Suche nach Aktualisierungen …", "Checking for updates …"},
                {"Ein anderer Update-Vorgang läuft bereits.", "Another update operation is already running."},
                {"Update-Prüfung", "Update check"},
                {"Kostenloses Update wird heruntergeladen", "Free update is downloading"},
                {"Update konnte nicht gestartet werden.", "The update could not be started."},
                {"Installation einmal erlauben", "Allow installation once"},
                {"Android braucht deine Freigabe, damit Ampere eine APK zur Installation übergeben darf. Es wird noch nichts heruntergeladen. Nach der Freigabe erscheint das Update hier erneut; Android fragt vor der Installation zusätzlich nach deiner Bestätigung.", "Android needs your permission before Ampere can hand over an APK for installation. Nothing is downloaded yet. After you allow it, the update will appear here again; Android will also ask for confirmation before installing."},
                {"Installationsfreigabe bitte in den App-Einstellungen aktivieren.", "Please enable installation permission in the app settings."},
                {"Update-Download fehlgeschlagen.", "Update download failed."},
                {"Update verworfen: Datei ist zu groß.", "Update discarded: file is too large."},
                {"Update-Datei konnte nicht geöffnet werden.", "The update file could not be opened."},
                {"Update verworfen: Hash, Version oder Release-Signatur ungültig.", "Update discarded: hash, version or release signature is invalid."},
                {"Update konnte nicht sicher gestartet werden.", "The update could not be started safely."},
                {"Bitte die heruntergeladene APK aus den Dateien öffnen.", "Please open the downloaded APK from Files."},
                {"Berechtigung fehlt", "Permission not granted"},
                {"App-Benachrichtigungen sind deaktiviert", "App notifications are disabled"},
                {"Kanal „Akkuüberwachung“ ist deaktiviert", "The “Battery monitoring” channel is disabled"},
                {"aktiviert", "Enabled"},
                {"uneingeschränkt", "Unrestricted"},
                {"vom System optimiert", "Optimized by the system"},
                {"Kein aktuelles Dienstsignal (letztes Signal älter als 30 Min. oder nicht verfügbar)", "No recent service signal (last signal is older than 30 minutes or unavailable)"},
                {"Dienst zuletzt gerade eben bestätigt", "Service confirmed just now"},
                {"Dienst zuletzt vor ", "Service last confirmed "},
                {" Min. bestätigt", " minutes ago"},
                {"Live-Benachrichtigung:", "Live notification:"},
                {"Hintergrunddienst:", "Background service:"},
                {"Akkuoptimierung:", "Battery optimization:"},
                {"Wenn kein aktuelles Dienstsignal vorliegt, öffne Ampere einmal; dabei wird die Überwachung neu gestartet.", "If there is no recent service signal, open Ampere once; monitoring will be restarted."},
                {"Android kann sie nach „Stopp erzwingen“ oder durch Hersteller-Energiesparregeln anhalten.", "Android may stop it after “Force stop” or because of manufacturer power-saving rules."},
                {"Ampere überwacht den Akku über einen sichtbaren Android-Dienst.", "Ampere monitors the battery through a visible Android service."},
                {"Sind Benachrichtigungen gesperrt, kann der Dienst trotzdem laufen, aber seine Live-Anzeige fehlt.", "The service may still run when notifications are blocked, but its live display is unavailable."},
                {"Energiesparfunktionen des Herstellers oder „Stopp erzwingen“ können die Überwachung anhalten.", "Manufacturer power-saving features or “Force stop” can stop monitoring."},
                {"Im Tiefschlaf darf Android Aktualisierungen verzögern; Ampere hält das Gerät bewusst nicht dauerhaft wach, um keinen zusätzlichen Akkuverbrauch zu verursachen.", "During deep sleep, Android may delay updates; Ampere deliberately does not keep the device awake to avoid extra battery use."},
                {"Ampere überwacht den Akku", "Ampere is monitoring your battery"},
                {"Akkubetrieb", "On battery"}, {"Akku entlädt", "Battery discharging"},
                {"Akkumesswerte werden auf diesem Gerät gespeichert", "Battery measurements are stored on this device"},
                {"Starte die Kapazitätsmessung getrennt vom Ladegerät unter 25 %.", "Start the capacity measurement unplugged and below 25%."},
                {"Gib die werkseitige Kapazität in mAh ein. Mit 0 wird automatisch der von Android gemeldete Wert verwendet.", "Enter the factory capacity in mAh. Enter 0 to use the value reported by Android automatically."},
                {"Akkustatus kopiert.", "Battery status copied."},
                {"Strom", "Current"}, {"Quelle", "Source"}, {"lokal auf Android", "local on Android"},
                {"Version", "Version"},
                {"Laden erkannt", "Charging detected"}, {"Bildschirm- und Hintergrundverbrauch lokal erfasst", "Screen and background usage recorded locally"},
                {"Lokale Akkuüberwachung · jede Sekunde", "Local battery monitoring · every second"},
                {"Prozent", "percent"}, {"Stunde", "hour"}, {"Stunden", "hours"},
                {"Minute", "minute"}, {"Minuten", "minutes"}, {"Tag", "day"}, {"Tage", "days"},
                {"Home measurement", "Start measurement"},
                // Resolve fragments after the broader vocabulary replacements above.
                {"Temperature alert · ab ", "Temperature alert · at "},
                {"Temperaturewarnung · ab ", "Temperature alert · at "},
                {"Low battery alert · bei ", "Low battery alert · at "},
                {"Data collection · alle ", "Data collection · every "},
                {"HISTORY & STATISTIK", "HISTORY & STATISTICS"},
                {"Batterieverbrauch", "Battery usage"}, {"Batterieverschleiß", "Battery wear"},
                {"Batteryverbrauch", "Battery usage"}, {"Batteryverschleiß", "Battery wear"},
                {"Geladen/Usage", "Charged/usage"},
                {"Laderate ", "Charge rate "}, {"Strom nicht verfügbar", "Current unavailable"},
                {"Temperatur nicht verfügbar", "Temperature unavailable"},
                {"Akkumesswerte werden auf diesem Gerät gespeichert", "Battery measurements are stored on this device"},
                {"Restenergie", "Remaining energy"}, {"Android-Zustand", "Android status"},
                {"Kapazitätsniveau", "Capacity level"}, {"Ladeprofil", "Charging profile"},
                {"Ladealgorithmus", "Charging algorithm"}, {"Ladeverhalten", "Charging behavior"},
                {"Thermik", "Thermal status"}, {"Gesundheit", "Health"}, {"Schätzung", "Estimate"},
                {"Lokale Akkuüberwachung", "Local battery monitoring"}, {"Laden erkannt", "Charging detected"},
                {"Bildschirm- und Hintergrundverbrauch lokal erfasst", "Screen and background usage recorded locally"},
                {"Akkuüberwachung", "Battery monitoring"}, {"Ladealarm", "Charge alert"},
                {"Batterystand", "Battery level"}, {"daye", "days"},
                {"History täglich", "Daily history"}, {"History wöchentlich", "Weekly history"},
                {"History monatlich", "Monthly history"}, {" von ", " of "},
                {"Charged/Usage", "Charge/usage ratio"}, {"Rate n/v", "Rate unavailable"},
                {"Battery level beim Home", "Battery level at start"},
                {"Battery level beim Start", "Battery level at start"},
                {"Battery level aktuell", "Current battery level"},
                // The broad navigation word "Start" must not alter "Starte ..." in dialogs.
                {"Homee die Kapazitätsmessung getrennt vom Ladegerät unter 25 %.", "Start the capacity measurement unplugged and below 25%."},
                {"Home a discharge session", "Start a discharge session"},
                {"Batterystatus kopiert.", "Battery status copied."},
                {"Since unplugging · geschätzte Werte", "Since unplugging · estimated values"},
                {"STROM", "CURRENT"}, {"LEISTUNG", "POWER"},
                {"Berühren zum Beenden", "Touch to exit"},
                // Correct compounds affected by the broad "Akku" replacement.
                {"Batteriebetrieb", "On battery"},
                {"Batterybetrieb", "On battery"},
                {"On battery aktiv", "On battery"}
        };
        for (String[] phrase : phrases) result = result.replace(phrase[0], phrase[1]);
        return result;
    }
}
