package com.ampere.batterylab;

import android.content.Context;
import android.content.res.Configuration;
import android.os.Build;
import java.util.Locale;

/** Small, dependency-free UI language layer used by the custom canvas and services. */
final class AppText {
    private AppText() {}

    static boolean isEnglish(Context context) {
        if (context == null) return "en".equalsIgnoreCase(Locale.getDefault().getLanguage());
        Configuration configuration = context.getResources().getConfiguration();
        Locale locale;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            locale = configuration.getLocales().isEmpty()
                    ? Locale.getDefault() : configuration.getLocales().get(0);
        } else {
            //noinspection deprecation
            locale = configuration.locale == null ? Locale.getDefault() : configuration.locale;
        }
        return "en".equalsIgnoreCase(locale.getLanguage());
    }

    static String t(Context context, String value) {
        return isEnglish(context) ? t(value) : value;
    }

    /**
     * Translates the UI vocabulary while preserving numbers, units, app names
     * and server-provided values. The method intentionally leaves unknown
     * strings untouched so diagnostics and user data are never corrupted.
     */
    static String t(String value) {
        if (value == null || value.isEmpty()
                || !"en".equalsIgnoreCase(Locale.getDefault().getLanguage())) return value;
        String result = value;
        String[][] phrases = {
                {"Beobachte deinen Akku", "Monitor your battery"},
                {"Akkuverbrauch deiner Apps", "Battery usage by app"},
                {"Dein Akku im Zeitverlauf", "Your battery over time"},
                {"Dein Tagesrhythmus", "Your daily pattern"},
                {"Akkugesundheit", "Battery health"},
                {"Akkukapazität", "Battery capacity"},
                {"Akkuzustand", "Battery status"},
                {"Akkuinformationen werden geladen.", "Loading battery information."},
                {"Alles läuft", "Everything is running"},
                {"ganz entspannt.", "smoothly."},
                {"Noch nicht gemessen", "Not measured yet"},
                {"Finde Kapazität und Verschleiß heraus.", "Measure capacity and battery wear."},
                {"Messung aktualisieren", "Refresh measurement"},
                {"Messung starten", "Start measurement"},
                {"Designkapazität", "Design capacity"},
                {"Gemessene Kapazität", "Measured capacity"},
                {"AKKUSTAND · AUTOMATISCH", "BATTERY LEVEL · AUTOMATIC"},
                {"AKKUSTAND · AUTOMATIK", "BATTERY LEVEL · AUTOMATIC"},
                {"AKKUGESUNDHEIT", "BATTERY HEALTH"},
                {"AKKUSTAND", "BATTERY LEVEL"},
                {"LÄDT JETZT", "CHARGING NOW"},
                {"AKKUBETRIEB", "ON BATTERY"},
                {"UNTERWEGS MIT AKKU", "ON THE GO"},
                {"DEIN AKKU-MUSTER", "YOUR BATTERY PATTERN"},
                {"DEIN AKKU-TAGEBUCH", "YOUR BATTERY JOURNAL"},
                {"LIVE & SITZUNG", "LIVE & SESSION"},
                {"APP-VERBRAUCH · GESCHÄTZT", "APP USAGE · ESTIMATED"},
                {"ALLE APP-DETAILS ANSEHEN  →", "VIEW ALL APP DETAILS  →"},
                {"Ø VERBRAUCH", "AVERAGE USAGE"},
                {"am Ende der Entladung", "at the end of discharge"},
                {"aktueller Akkustand", "current battery level"},
                {"Gerät wird geladen", "Device is charging"},
                {"Sitzung startet beim Abstecken", "Session starts when unplugged"},
                {"Bildschirm an", "Screen on"}, {"Bildschirm aus", "Screen off"},
                {"Bildschirm an / aus", "Screen on / off"},
                {"Nach dem Abstecken", "After unplugging"},
                {"Normale Nutzung", "Normal use"}, {"Mehr Daten", "More data"},
                {"seit dem Abstecken", "since unplugging"},
                {"Seit dem Abstecken", "Since unplugging"},
                {"Seit dem Abstecken · geschätzte Werte", "Since unplugging · estimated values"},
                {"Ø Entladerate", "Average discharge rate"}, {"Entladerate", "Discharge rate"},
                {"Tiefschlaf", "Deep sleep"},
                {"Verbrauch seit dem Abstecken", "Usage since unplugging"},
                {"LIVE · GERÄT", "LIVE · DEVICE"},
                {"LADEBEGLEITUNG", "CHARGE COMPANION"},
                {"AKTUELL", "CURRENT"},
                {"RATE JETZT", "CURRENT RATE"},
                {"TEMPERATUR · SPANNUNG", "TEMPERATURE · VOLTAGE"},
                {"SENSOREN", "SENSORS"},
                {"Volle Kapazität", "Full capacity"},
                {"Nennkapazität", "Design capacity"},
                {"Nennwert", "Design value"},
                {"Alarm bei", "Alert at"},
                {"kein Ladestopp", "no charge stop"},
                {"Laden im Blick.", "Charging at a glance."},
                {"Bereit zum Laden.", "Ready to charge."},
                {"Fortschritt zum Ladeziel", "Progress toward charge target"},
                {"Benachrichtigt dich bei", "Notifies you at"},
                {"Zurzeit ausgeschaltet", "Currently disabled"},
                {"Live-Anzeige", "Live overlay"},
                {"Schwebt über anderen Apps", "Floats over other apps"},
                {"Über anderen Apps ausgeblendet", "Hidden over other apps"},
                {"Quelle: ", "Source: "},
                {"Status · Quelle", "Status · source"},
                {"Zeit bis Ladeziel", "Time to charge target"},
                {"Länger laden für eine Schätzung", "Charge longer for an estimate"},
                {"AKKUVERBRAUCH", "BATTERY USAGE"},
                {"ÄNDERUNG", "CHANGE"}, {"DAUER", "DURATION"}, {"GESTARTET", "STARTED"},
                {"GESCHÄTZTE RESTLAUFZEIT BIS 0 %", "ESTIMATED TIME REMAINING TO 0%"},
                {"Noch keine Messung", "No measurement yet"},
                {"Eine volle Ladung", "A full charge"},
                {"SYSTEMDATEN AKTIV", "SYSTEM DATA ACTIVE"},
                {"SO ENTSTEHT DIE SCHÄTZUNG", "HOW THE ESTIMATE IS CALCULATED"},
                {"NENNKAPAZITÄT", "DESIGN CAPACITY"},
                {"ANTIPPEN ZUM ÄNDERN", "TAP TO EDIT"},
                {"Nur lokal gespeichert.", "Stored locally only."},
                {"PRIVAT VON ANFANG AN", "PRIVATE BY DESIGN"},
                {"ANALYSEZENTRALE", "ANALYSIS CENTER"},
                {"LADEVORGANG", "CHARGING SESSION"},
                {"LADEMENGE", "CHARGE AMOUNT"},
                {"VERBLEIBENDE NUTZUNGSZEIT", "REMAINING RUNTIME"},
                {"KAPAZITÄTSSCHÄTZUNG", "CAPACITY ESTIMATE"},
                {"LADEGESCHWINDIGKEIT", "CHARGING SPEED"},
                {"ENTLADEVORGANG", "DISCHARGE SESSION"},
                {"An ", "On "}, {" · aus ", " · off "},
                {"Bildschirm-Aufweckungen", "screen wake-ups"},
                {"TÄGLICHE VOLLZYKLEN", "DAILY FULL CYCLES"},
                {"LADEVERSCHLEISS", "CHARGING WEAR"},
                {"AUSWERTUNG", "ANALYSIS"}, {"LETZTE SITZUNGEN", "RECENT SESSIONS"},
                {"VERLAUF", "HISTORY"}, {"DIAGNOSE", "DIAGNOSTICS"},
                {"Sitzungen:", "Sessions:"}, {"Ladungsmenge:", "Charge amount:"},
                {"VERLAUF & STATISTIK", "HISTORY & STATISTICS"},
                {"Lokal aus Messpunkten berechnet · keine Cloud", "Calculated locally from measurements · no cloud"},
                {"DIESER MONAT · MONATSANFANG BIS HEUTE", "THIS MONTH · START OF MONTH TO TODAY"},
                {"Aufgeladen", "Charged"}, {"Batterieverbrauch", "Battery usage"},
                {"Geladen/Usage", "Charged/usage"},
                {"Woche", "Week"}, {"Monat", "Month"}, {"day", "Day"},
                {"Werte des aktiven Bereichs", "Values for the active section"},
                {"Gut lesbare Akkuwerte · live aktualisiert", "Readable battery values · updated live"},
                {"Berechtigungen & Zugriffe", "Permissions & access"},
                {"App-Akkuverbrauch", "App battery usage"},
                {"Akku-Bilanz", "Battery balance"},
                {"Sitzungsdetails", "Session details"},
                {"Letzte 24 Stunden", "Last 24 hours"},
                {"Letzte 7 Tage", "Last 7 days"},
                {"Letzte 30 Tage", "Last 30 days"},
                {"Täglich", "Daily"}, {"Wöchentlich", "Weekly"}, {"Monatlich", "Monthly"},
                {"Übersicht", "Overview"}, {"Start", "Home"}, {"Laden", "Charging"},
                {"Entladen", "Discharging"}, {"Akku", "Battery"}, {"Verlauf", "History"},
                {"Gesundheit", "Health"}, {"Einstellungen", "Settings"},
                {"Aktionen", "Actions"}, {"Ladeziel", "Charge target"},
                {"Akkustand", "Battery level"}, {"Akkustrom", "Battery current"},
                {"Akkuspannung", "Battery voltage"}, {"Akkuleistung", "Battery power"},
                {"Akkutemperatur", "Battery temperature"}, {"Temperatur", "Temperature"},
                {"Spannung", "Voltage"}, {"Verbrauch", "Usage"}, {"Akkuverbrauch", "Battery usage"},
                {"Verbrauchte Ladung", "Charge used"}, {"Verbrauchte Energie", "Energy used"},
                {"Geladen/Verbrauch", "Charged/used"}, {"Akkuverschleiß", "Battery wear"},
                {"Verschleiß", "Wear"}, {"Effizienz", "Efficiency"}, {"Sitzungen", "Sessions"},
                {"Ladeeingang", "Charging input"}, {"Akkuseite", "Battery side"},
                {"Aktueller Akkustand", "Current battery level"}, {"aktueller Akkustand", "current battery level"},
                {"Aktualisiert live", "Updated live"}, {"Warte auf Strommessung", "Waiting for current measurement"},
                {"Warte auf Android-Akkuwert", "Waiting for Android battery value"},
                {"Nicht verfügbar", "Not available"}, {"nicht verfügbar", "not available"},
                {"Keine Daten", "No data"}, {"Noch keine Daten", "No data yet"},
                {"Noch keine Verbrauchsdaten für die Quote", "No usage data for the ratio yet"},
                {"Wird gemessen", "Measuring"}, {"Noch offen", "Pending"}, {"gerade eben", "just now"},
                {"BERECHNET", "CALCULATED"}, {"GESCHÄTZT", "ESTIMATED"}, {"SYSTEM", "SYSTEM"},
                {"LIVE", "LIVE"}, {"AKKUVERBRAUCH", "BATTERY USAGE"}, {"Lade-/Verbrauchsquote", "charge/usage ratio"},
                {"lokale Verlaufseinträge zu erstellen.", "to create local history entries."},
                {"Akkumesswerte bleiben auf diesem Gerät.", "Battery measurements stay on this device."},
                {"Weitere Sitzungen im Verlauf", "More sessions in history"},
                {"Verbrauch den verwendeten Apps zu.", "Usage attributed to the apps used."},
                {"Wärme prüfen", "Check temperature"}, {"Unbekannt", "Unknown"},
                {"Temperaturwarnung", "Temperature alert"}, {"Tiefstandwarnung", "Low battery alert"},
                {"Datenerfassung", "Data collection"}, {"Hintergrundüberwachung", "Background monitoring"},
                {"Daten & Datenschutz", "Data & privacy"}, {"Nutzungsanalyse", "Usage analytics"},
                {"Sicherung & Wiederherstellung", "Backup & restore"},
                {"Benachrichtigungen", "Notifications"}, {"Berechtigungen prüfen", "Check permissions"},
                {"Ladeziel & Ladealarm", "Charge target & alert"}, {"Overlay-Berechtigung", "Overlay permission"},
                {"Nach Updates suchen", "Check for updates"}, {"Kurzanleitung", "Quick guide"},
                {"Aktuellen Status kopieren", "Copy current status"}, {"Aktuellen Status teilen", "Share current status"},
                {"Gesundheitsbasis zurücksetzen", "Reset health baseline"},
                {"Temperaturwarnung · ab ", "Temperature alert · at "}, {"Temperaturwarnung · aus", "Temperature alert · off"},
                {"Tiefstandwarnung · bei ", "Low battery alert · at "}, {"Tiefstandwarnung · aus", "Low battery alert · off"},
                {"Datenerfassung · alle ", "Data collection · every "}, {"Minuten", "minutes"},
                {"Temperaturwarnung · Rücksetzung 3 °C darunter", "Temperature alert · resets 3 °C below"},
                {"Tiefstandwarnung · Rücksetzung mit 3 % Abstand", "Low battery alert · resets with a 3% margin"},
                {"Datenerfassung · nur lokal", "Data collection · local only"},
                {"Aus", "Off"}, {"Ab ", "At "}, {"Bei ", "At "}, {"oder weniger", "or less"},
                {"(empfohlen)", "(recommended)"}, {"Alle ", "Every "},
                {"Abbrechen", "Cancel"}, {"Speichern", "Save"}, {"Schließen", "Close"},
                {"Einstellungen schließen", "Close settings"}, {"Akku-Einstellungen", "Battery settings"},
                {"Berechtigungen & Zugriffe", "Permissions & access"}, {"Fertig", "Done"},
                {"Aktiv", "Active"}, {"Nicht erteilt", "Not granted"}, {"optional", "optional"},
                {"Optional · nicht aktiviert", "Optional · not enabled"},
                {"Live-Status und Alarme", "Live status and alerts"},
                {"App-Nutzungszugriff", "App usage access"}, {"Verbrauch je App", "Usage by app"},
                {"Nicht erteilt · optional", "Not granted · optional"},
                {"Overlay", "Overlay"}, {"Live-Anzeige", "Live overlay"},
                {"Einige Zugriffe fehlen oder wurden von Android zurückgesetzt.", "Some accesses are missing or were reset by Android."},
                {"Ampere prüft sie beim Öffnen erneut", "Ampere checks them again when opened"},
                {"abgelehnte optionale Zugriffe melden wir höchstens monatlich.", "we remind you about declined optional accesses at most once a month."},
                {"Widerrufe erkennen wir beim nächsten Öffnen.", "We detect revoked access the next time you open the app."},
                {"Benachrichtigungen ermöglichen Live-Status und Ladealarme.", "Notifications enable live status and charge alerts."},
                {"App-Nutzungszugriff zeigt den Verbrauch je App", "App usage access shows usage by app"},
                {"Overlay zeigt die Live-Anzeige über anderen Apps.", "Overlay shows the live display over other apps."},
                {"Diese beiden Zugriffe sind optional.", "These two accesses are optional."},
                {"Ampere prüft den Status beim Öffnen erneut.", "Ampere checks their status again when opened."},
                {"Tippe auf einen Eintrag, um ihn zu ändern.", "Tap an entry to change it."},
                {"Temperaturwarnung ausgeschaltet", "Temperature alert turned off"},
                {"Tiefstandwarnung ausgeschaltet", "Low battery alert turned off"},
                {"Hintergrundüberwachung ist ab Android 6 verfügbar.", "Background monitoring is available from Android 6."},
                {"Einstellungen", "Settings"},
                {"Lokale Daten löschen?", "Delete local data?"},
                {"Gesundheitsbasis zurücksetzen?", "Reset health baseline?"},
                {"Backup gespeichert.", "Backup saved."}, {"Backup wiederhergestellt.", "Backup restored."},
                {"CSV-Export gespeichert.", "CSV export saved."}, {"Diagnosebericht gespeichert.", "Diagnostic report saved."},
                {"Forschungs-Export gespeichert.", "Research export saved."},
                {"Live-Daten aktualisiert.", "Live data updated."},
                {"Akkuüberwachung", "Battery monitoring"}, {"Ladealarm", "Charge alert"},
                {"Ampere überwacht den Akku", "Ampere is monitoring your battery"},
                {"Akkubetrieb", "On battery"}, {"Akku entlädt", "Battery discharging"},
                {"Akkumesswerte werden auf diesem Gerät gespeichert", "Battery measurements are stored on this device"},
                {"Laden erkannt", "Charging detected"}, {"Bildschirm- und Hintergrundverbrauch lokal erfasst", "Screen and background usage recorded locally"},
                {"Lokale Akkuüberwachung · jede Sekunde", "Local battery monitoring · every second"},
                {"Prozent", "percent"}, {"Stunde", "hour"}, {"Stunden", "hours"},
                {"Minute", "minute"}, {"Minuten", "minutes"}, {"Tag", "day"}, {"Tage", "days"},
                {"Home measurement", "Start measurement"},
                // Resolve fragments after the broader vocabulary replacements above.
                {"Temperature alert · ab ", "Temperature alert · at "},
                {"Low battery alert · bei ", "Low battery alert · at "},
                {"Data collection · alle ", "Data collection · every "}
        };
        for (String[] phrase : phrases) result = result.replace(phrase[0], phrase[1]);
        return result;
    }
}
